<?php

/**
 * @file
 * Contains month_year.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function month_year_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the month_year module.
    case 'help.page.month_year':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide a Month Year field type') . '</p>';
      return $output;

    default:
  }
}
